# Generated by Django 3.0.6 on 2020-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('price_sm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_lg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
